### ISSUE TITLE
Using some storage to keep statistic results

### ISSUE THREAD

**Issue by eignatik** [eignatik/LOAD.x#47]
## Problem
During the execution there is a need to store some test results somehow. 

## Todo
- [x] pick up some lightweight DB for statistics

create basic storage handlers:
- [x] design DB structure
- [x] design domain objects 
- [x] create CRUD using Hibernate ORM
- [x] create the package to store scripts and rollbacks

**Comment by eignatik** [comment]
The SQLite has been picked up as local storage
